apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-credentials-secret
  # namespace:
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: aws-secretstore
    kind: SecretStore
  target:
    name: db-credentials
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: automobiles-database-credentials
