apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: simple-autos-external-secret
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: aws-secrets-store-credentials
    kind: SecretStore
  target:
    name: db-credentials
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: automobiles-database-credentials