apiVersion: v1
kind: Service
metadata:
  name: simple-autos-service
spec:
  selector:
    app: simple-autos
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
